extends Node

signal poop_spawned
signal poop_cleaned
signal creature_fed
signal creature_died
signal creature_petted
signal creature_became_hungry
signal creature_became_starving
signal creature_became_lonely
signal creature_became_abandoned
