name: Game Jam Task
title: "[Game Jam Task] "
description: Template for creating a new game jam task.
labels: game-jam
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ### Prepopulated Text
        Use this template to document your game jam task.

        - **Reminder**: Stick to your game jam theme!
        - **Include Details**: Clearly outline the steps needed to complete this task.

        Below is the form to fill out:
  - type: input
    id: task-title
    attributes:
      label: Task Title
      description: Provide a short title for the task.
      placeholder: e.g., Create player character movement
  - type: textarea
    id: task-description
    attributes:
      label: Task Description
      description: Provide a detailed description of the task.
      placeholder: Describe what needs to be done.
  - type: textarea
    id: suuubtasks
    attributes:
      label: Task Description
      description: Provide a detailed description of the task.
      placeholder: Describe what needs to be done.
      value: |
        ## Acceptance Criteria:

        - [ ] The model is saved in `.gltf` file format.
        - [ ] The model is saved to the specified filepath: `{{file_path}}`.
        - [ ] The model is opened in Godot to generate the `.import` file.
        - [ ] The file has been imported in godot (Godot opened) and has the accompanying `.import` file.
        - [ ] A pull request (PR) is created with the changes.
  - type: dropdown
    id: task-priority
    attributes:
      label: Priority
      description: Select the priority level of the task.
      options:
        - Low
        - Medium
        - High
