name: Build and Push Validate GLTF Container

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'tools/gltf-validator/**'

permissions:
  contents: read
  packages: write

jobs:
  build-push-validate-gltf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and cache Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./tools/gltf-validator
          push: true
          tags: ghcr.io/screwloose-games/gltf-validator:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max