name: GLTF Validator

on:
  pull_request:
    paths:
      - '**/*.gltf'
      - '**/*.glb'
      - '**/*.spec.yaml'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for comparing changes

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy pygltflib trimesh pyrender pillow pyyaml

      - name: Find changed GLTF files
        id: changed-files
        run: |
          # Get list of changed files
          git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} > changed_files.txt
          
          # Filter for GLTF files and their spec files
          grep -E '\.(gltf|glb)$' changed_files.txt > gltf_files.txt
          
          # Create output directory
          mkdir -p validation_output
          
          # Run validator on each file
          if [ -s gltf_files.txt ]; then
            python tools/gltf-validator/validate_gltf.py validation_output $(cat gltf_files.txt)
          else
            echo "No GLTF files changed"
            exit 0
          fi

      - name: Upload validation results
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: validation-results
          path: validation_output/

      - name: Create GitHub comment
        uses: actions/github-script@v6
        if: success()
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            // Read the comment file
            const commentPath = path.join('validation_output', 'github_comment.md');
            if (fs.existsSync(commentPath)) {
              const comment = fs.readFileSync(commentPath, 'utf8');
              
              // Create or update comment
              const { data: comments } = await github.rest.issues.listComments({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number
              });
              
              const botComment = comments.find(c => c.user.login === 'github-actions[bot]' && c.body.includes('GLTF Validation Results'));
              
              if (botComment) {
                await github.rest.issues.updateComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  comment_id: botComment.id,
                  body: comment
                });
              } else {
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  body: comment
                });
              }
            } 